# Generated by Django 4.1.5 on 2023-01-28 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('api_url', models.URLField(blank=True, max_length=255)),
                ('scraped_id', models.IntegerField(null=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('ean', models.CharField(blank=True, max_length=50)),
                ('brand_name', models.CharField(blank=True, max_length=50)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('unit_type', models.CharField(blank=True, max_length=10)),
                ('conversion', models.CharField(blank=True, max_length=10)),
                ('conversion_unit', models.CharField(blank=True, max_length=10)),
                ('qty_per_package', models.IntegerField(null=True)),
                ('tax_rate', models.CharField(blank=True, max_length=10)),
                ('category_path', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_scrape', models.DateTimeField(blank=True, null=True)),
                ('parrent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLocalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField(null=True)),
                ('stock_status', models.IntegerField(null=True)),
                ('availability', models.CharField(blank=True, max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_scrape', models.DateTimeField(blank=True, null=True)),
                ('parrent_local_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.localstore')),
                ('parrent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_scrape', models.DateTimeField(blank=True, null=True)),
                ('parrent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
