# Generated by Django 4.1.5 on 2023-01-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_default_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocaldata',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
